#!/usr/bin/env bash



############## User-Config ---- do your edits ##########################

APPNAME="$(basename "$0" )"

#Choose a main location
MAIN_LOCATION="UK"
PROBABILITY_MAIN_LOCATION=50					#0=Off 1-99=maybe 100=always

#Add or delete countrys
#You should not reuse MAIN_LOCATION 
RANDOM_POOL=(
"SI"
"SO"
"ZA"
"KR"
"SS"
"ES"
"LK"
)

PROBABILITY_SECURECORE=50						#0=Off 1-99=maybe 100=on

SWITCH_VPN_ONOFF="ON"
SECONDS_SWITCH_VPN_MAX=7200
SECONDS_SWITCH_VPN_MIN=3600

 
NOTIFY_ALLOFF="NO" 							#use OFF to mute all NOTIFY_						
NOTIFY_VPN_ERROR_ONOFF="ON"
NOTIFY_VPN_OK_ONOFF="ON"
NOTIFY_EXIT_ONOFF="ON"
NOTIFY_ASK_ONOFF="ON" 
PROTON_INFO_ONOFF="ON"
START_MESSAGE_ONOFF="ON"

#Allowed retries after the first connection failure
MAX_CON_FAILS=3									

########################################################################
#----------------------------------------------------------------------#

TXT_EXIT_HANDLER="$APPNAME stopped!"
TXT_SWITCH_OFF="VPN Switch off." 
TXT_SLEEP_HANDLER="seconds to change connection"

TXT_CON_FAILED="Connection failed more than $MAX_CON_FAILS"
TXT_CON_ERROR="Connection with server failed"
TXT_CON_OK="Connected with server"

TXT_KILLSWITCH_ERROR="Critical Error: kill-switch on failed!"
TXT_LOCKFILE_ERROR="Lockfile could not opened."
TXT_RUN_ERROR="already run"

TXT_REQUIRED_PROTON="Protonvpn is missing."
TXT_REQUIRED_NOTIFY="notify-send is missing - try: sudo apt install libnotify-bin"
TXT_REQUIRED_TPUT="tput is missing - try: sudo apt install ncurses-bin"
TXT_REQUIRED_AWK="awk is missing - try: sudo apt install mawk"

TXT_ASK_KILLSWITCH_A="Proton Kill-Switch is off"
TXT_ASK_KILLSWITCH_B="Disconnect, enable it, and reconnect?"

TXT_MESSAGE_START="Proton VPN commands remain available while the script is running.
Press Ctrl+C to stop the protonvpn random script.
Stopping proton-random does not disconnect the active VPN connection.

Thank you for choosing proton-random.
"

#------------ Error codes ---------------------------------------------#

#10 = Missing Dependency
#11 = Invalid Config
#12 = kill-switch on failed

#---------------Function T-Out ----------------------------------------#
Out(){
	local text="$1"
	RunInTerminal && printf "%s\n" "$text"
}

OutErr(){
	local text="$1"
	RunInTerminal && printf '\033[38;5;196m%s\033[0m\n' "$text"
}

OutH1() {
	local text="$1"
	RunInTerminal && printf '\n\033[38;5;38m%s\033[0m\n' "$text"
}

#---------------Function ----------------------------------------------#
EnsureSingleInstance(){
	local lockfile
	lockfile="${XDG_RUNTIME_DIR:-/tmp}/${APPNAME}.${UID}.lock"

exec 9>"$lockfile" || {
    OutErr "$TXT_LOCKFILE_ERROR" >&2
    exit 1
}

if ! flock -n 9; then
    OutErr "$TXT_RUN_ERROR $APPNAME" >&2
    exit 1
fi
}

RunInTerminal(){
if ! { [[ -t 1 && -n ${TERM:-} ]] && tput cols >/dev/null 2>&1; } then
	return 1
fi
}


#--------------- Functions calling protonvpn --------------------------#

KillSwitchOn(){
	if ! protonvpn config set kill-switch standard; then
		ExitHandler 12 "$TXT_KILLSWITCH_ERROR"
	fi
}

DisconnectVpn(){
	protonvpn disconnect
}

VpnInfo(){
	[[ "$PROTON_INFO_ONOFF" == "ON" ]] && protonvpn
}

#-------------- Functions KillSwitchGuard -----------------------------#

AskPermissionKillSwitch(){
	local usrinp
	if [[ "$NOTIFY_ALLOFF" = "OFF" || "$NOTIFY_ASK_ONOFF" = "OFF" ]]; then
		if RunInTerminal; then
			while true; do
				read -rp "Enter: y or n >>" usrinp
				usrinp="${usrinp,,}"
				case "$usrinp" in
					y|yy|ye|yes)
						return 0
					;;	
					n|nn|no)
						return 1
					;;
				esac
			done
		fi
	else
		NotifyAsk "$TXT_ASK_KILLSWITCH_A" "$TXT_ASK_KILLSWITCH_B"
	fi
}
		
CheckConnection(){
	local status
	status="$(protonvpn status | awk 'tolower($0) ~ /status/ { print $2; exit }')"
	[[ "${status,,}" == "connected" ]] || return 1
}

CheckKillSwitch(){
	local killswitch
	killswitch="$( protonvpn config list   | awk 'tolower($0) ~ /kill-switch/ { print $2; exit }' )"
	[[ "${killswitch,,}" == "standard" ]] || return 1	
}

KillSwitchGuard(){
	if ! CheckKillSwitch; then
		if CheckConnection; then
			if AskPermissionKillSwitch; then
				DisconnectVpn
				KillSwitchOn
			fi
		else
			KillSwitchOn
		fi
	fi
}

#-------------- Functions validate script start  ----------------------#
	
DepCheck(){
	local dep="$1"
	if ! command -v "$dep" &>/dev/null ; then
		return 1
	fi
}

ValCountry(){
	local -a pool=("$@")
	local element
	(("${#pool[@]}" > 0 )) || return 1
	 
	for element in "${pool[@]}"; do
		[[ "$element" =~ ^[A-Z]{2}$ ]] || return 1
	done
}

ValOnOff(){
	local -a strings=("$@")
	local element
	for element in "${strings[@]}"; do
		[[ "$element" == "ON" || "$element" == "OFF" || "$element" == "NO" ]] || \
		 return 1
	done
}

ValInteger(){
	local -a integers=("$@")
	local element
	
	for element in "${integers[@]}"; do
		[[ "$element" =~ ^[0-9]+$ ]] || return 1
	done
}

ValPercentage(){
	local -a percent=("$@")
	local element
	
	for element in "${percent[@]}"; do
		(( element >= 0 && element <= 100 )) || return 1
	done
}

ValConfig(){
	if ! ValCountry "$MAIN_LOCATION"; then
		return 1
	fi
	
	if ! ValCountry "${RANDOM_POOL[@]}"; then
		return 1
	fi
	
	if ! ValOnOff "$SWITCH_VPN_ONOFF" "$NOTIFY_ALLOFF" "$NOTIFY_VPN_ERROR_ONOFF" \
	"$NOTIFY_VPN_OK_ONOFF" "$NOTIFY_EXIT_ONOFF" "$NOTIFY_ASK_ONOFF" "$PROTON_INFO_ONOFF" \
	"$START_MESSAGE_ONOFF" ; then
		return 1
	fi
	
	
	if ! ValInteger "$SECONDS_SWITCH_VPN_MAX" "$SECONDS_SWITCH_VPN_MIN" \
	"$PROBABILITY_SECURECORE" "$PROBABILITY_MAIN_LOCATION" "$MAX_CON_FAILS"
	then
		return 1
	fi
	
	if ! ValPercentage "$PROBABILITY_SECURECORE" "$PROBABILITY_MAIN_LOCATION"; then
		return 1
	fi
	
	[[ "$SWITCH_VPN_ONOFF" == "ON" || "$SWITCH_VPN_ONOFF" == "OFF" ]] || return 1
	(( SECONDS_SWITCH_VPN_MIN < SECONDS_SWITCH_VPN_MAX )) || return 1
	
}

#------------------Functions Notify -----------------------------------#

NotifyVpnError(){
	[[ "$NOTIFY_VPN_ERROR_ONOFF" == "ON" ]] || return 0
	local server="$1"
	notify-send --urgency=critical --app-name="$APPNAME" -- "$APPNAME" "${TXT_CON_ERROR}: $server"
}

NotifyVpnOk() {
	[[ "$NOTIFY_VPN_OK_ONOFF" == "ON" ]] || return 0
	local server="$1"
	notify-send --urgency=normal  --expire-time=10000 --app-name="$APPNAME" -- "$APPNAME" "${TXT_CON_OK} : $server"
}

NotifyAsk(){
	local title="$1"
	local question="$2"
	usrinp=$( notify-send --urgency=critical --app-name="$APPNAME" --action="y=yes" --action="n=no"  "$title" "$question" )
	[[ "$usrinp" == "y" ]] || return 1
}

MessageStart(){
	if RunInTerminal; then
		VpnInfo
		OutH1 "$TXT_MESSAGE_START"
	fi
}
		
		
#----------------- Functions randomizing -------------------------------#

RandomPercent(){
		printf  "%s\n" "$(( RANDOM % 100 + 1 ))"
	}
	
RandomizeVpn(){
	local r
	local rr
	local country
	local -a securecore=()
	
	r="$( RandomPercent )"
	if (( r <= PROBABILITY_MAIN_LOCATION )); then
		country="$MAIN_LOCATION"
	else
		r="$(( RANDOM % ${#RANDOM_POOL[@]} ))"
		country="${RANDOM_POOL[$r]}"
	fi
	
	
	
	rr="$( RandomPercent )"
	(( rr <= PROBABILITY_SECURECORE )) && securecore+=("--securecore")
	
	if protonvpn connect "${securecore[@]}" --country "$country"; then
		NotifyVpnOk "$country"
		return 0
	else
		NotifyVpnError "$country"
		return 1
	fi
}

RandomizeSwitchTime(){
	local max="$1"
	local min="$2"
	local seconds
	
	seconds=$(( RANDOM % (max - min + 1) + min ))	
	printf "%s" "$seconds" 
}

#--------------- Functions Handler ------------------------------------#

SleepHandler(){
		local seconds="$1"
		local i
		if RunInTerminal; then	
			for (( i=0; i < seconds; i++ )); do
				Out "-- $(( seconds - i )) -- $TXT_SLEEP_HANDLER "
				sleep 1
				tput cuu1
				tput el
			done
		else
			sleep "$seconds"
		fi
	}
	
ExitHandler(){
	local errcode="$1"
	local text="$2"
	
	if DepCheck "notify-send"; then
		[[ "$NOTIFY_EXIT_ONOFF" == "ON" ]] && \
		notify-send --urgency=critical --app-name="$APPNAME" "$APPNAME" "$text - $TXT_EXIT_HANDLER"
	fi
	
	if (( errcode < 1 )); then
		Out "$text"
	else
		OutErr "$text"
	fi
	
	exit "$errcode"
}

#----------------------------------------------------------------------#



main(){
	local count_fails=0
	local wait_retry=1
	
	EnsureSingleInstance
	
	MessageStart
	while true; do
		
		KillSwitchGuard
		
		if  RandomizeVpn; then
			[[ "$SWITCH_VPN_ONOFF" == "OFF" ]] && ExitHandler 0 "$TXT_SWITCH_OFF"
			count_fails="0"
		else
			count_fails="$(( count_fails + 1 ))"
			wait_retry=$(( count_fails * 5 ))
			(( count_fails <= MAX_CON_FAILS )) || ExitHandler 1 "$TXT_CON_FAILED"
			sleep "$wait_retry"
			continue
		fi
		SleepHandler "$( RandomizeSwitchTime $SECONDS_SWITCH_VPN_MAX $SECONDS_SWITCH_VPN_MIN )"
			
	done
}

#----------------------------------------------------------------------#
ValConfig || ExitHandler 11 "Well played... You made the config invalid"

if [[ "$NOTIFY_ALLOFF" == "OFF" ]]; then
	NOTIFY_VPN_ERROR_ONOFF="OFF"
	NOTIFY_VPN_OK_ONOFF="OFF"
	NOTIFY_EXIT_ONOFF="OFF"
elif [[ "$NOTIFY_ALLOFF" == "ON" && \
	"$NOTIFY_VPN_ERROR_ONOFF" == "OFF" && \
	"$NOTIFY_VPN_OK_ONOFF" == "OFF" && \
	"$NOTIFY_EXIT_ONOFF" == "OFF" && \
	"$NOTIFY_ASK_ONOFF" == "OFF" ]]; then
	NOTIFY_ALLOFF="OFF"
fi

[[ "$NOTIFY_ALLOFF" != "OFF" ]] && \
{ DepCheck "notify-send" || ExitHandler 10  "$TXT_REQUIRED_NOTIFY"; }
DepCheck "tput" || ExitHandler 10  "$TXT_REQUIRED_TPUT"
DepCheck "awk" || ExitHandler 10 "$TXT_REQUIRED_AWK"
DepCheck "protonvpn" || ExitHandler 10 "$TXT_REQUIRED_PROTON"

main
