#!/usr/bin/env bash



############## User-Config ---- do your edits ##########################
APPNAME="$(basename "$0" )"


MODE="RANDOM"
MAIN_LOCATION="DE"
PROBABILITY_MAIN_LOCATION=5					

RANDOM_POOL=(
"US"
"Washington"
"NO"
"IQ"
)

SWITCH_VPN_ONOFF="ON"
SECONDS_SWITCH_VPN_MAX=10800
SECONDS_SWITCH_VPN_MIN=600

PROBABILITY_SECURECORE=0
						
NOTIFY_ALLOFF="NO" 												
NOTIFY_VPN_ERROR_ONOFF="ON"
NOTIFY_VPN_OK_ONOFF="ON"
NOTIFY_EXIT_ONOFF="ON"
NOTIFY_ASK_ONOFF="ON" 
PROTON_INFO_ONOFF="ON"
START_MESSAGE_ONOFF="ON"

MAX_CON_FAILS=2
INCREASING_DELAY=10									

########################################################################
#----------------------------------------------------------------------#

TXT_EXIT_HANDLER="$APPNAME stopped!"
TXT_SWITCH_OFF="VPN Switch off." 
TXT_SLEEP_HANDLER="seconds to change connection"

TXT_CON_FAILED="Connection failed more than $MAX_CON_FAILS"
TXT_CON_ERROR="Connection with server failed"
TXT_CON_OK="Connected with server"

TXT_KILLSWITCH_ERROR="Critical Error: kill-switch on failed!"
TXT_LOCKFILE_ERROR="Lockfile could not opened."
TXT_RUN_ERROR="already run"

TXT_REQUIRED_PROTON="Protonvpn is missing."
TXT_REQUIRED_NOTIFY="notify-send is missing - try: sudo apt install libnotify-bin"
TXT_REQUIRED_TPUT="tput is missing - try: sudo apt install ncurses-bin"
TXT_REQUIRED_AWK="awk is missing - try: sudo apt install mawk"

TXT_ASK_KILLSWITCH_A="Proton Kill-Switch is off"
TXT_ASK_KILLSWITCH_B="Disconnect, enable it, and reconnect?"


TXT_THANK_YOU="Thank you for choosing protonvpn-random."
TXT_MESSAGE_START="Proton VPN commands remain available while the script is running.
Press Ctrl+alt+c or close terminal to stop the protonvpn random script.
Stopping protonvpn-random does not disconnect the active VPN connection.

$TXT_THANK_YOU
"

TXT_HELP_R="Start in random mode"
TXT_HELP_L="Start in route(lane) mode"
TXT_HELP_B="Start script and keep it running in the background even if terminal is closed"
TXT_HELP_H="Show this help snippet"

#------------ Error codes ---------------------------------------------#

#10 = Missing Dependency
#11 = Invalid Config
#12 = kill-switch on failed


############### commandline options ####################################

RunBackground(){
    "$0" >/dev/null & PID=$!
    printf "%s\n" "$APPNAME will run in the background, you can close this terminal.
To stop application type: 'kill -9 $PID' in any terminal. 

$TXT_THANK_YOU"
    disown $PID 2>/dev/null
    exit 0
}

#--------------- Function help ----------------------------------------#

Help(){
    local help
    read -r -d '' help << EOM
Usage: $APPNAME [options]
  -r 			   $TXT_HELP_R
  -l			   $TXT_HELP_L
  -b               $TXT_HELP_B
  -h --help        $TXT_HELP_H
EOM
    echo "$help"
    exit
}

#--------------- Function set -----------------------------------------#
SetRandomMode(){
	MODE="RANDOM"
}

SetRouteMode(){
	MODE="ROUTE"
}

#---------------Function ParseCommandLineOptions ----------------------#

ParseCommandLineOptions(){
	local cli_options=("$@")
	options=$(getopt -o hbrl --long help -- "${cli_options[@]}")
	[[ $? -eq 0 ]] || help
	eval set -- "$options"
	while true; do
		case "$1" in
			-h|--help) Help; break;;
			-r) SetRandomMode; shift;;
			-l) SetRouteMode; shift;;
			-b) RunBackground; shift;;
			--) break;;
			*) shift;;
		esac
	done
}

################ Validate ##############################################
	
DepCheck(){
	local dep="$1"
	if ! command -v "$dep" &>/dev/null ; then
		return 1
	fi
}

ValCountry(){
	local -a country="$1"
	[[ "$country" =~ ^[A-Z]{2}$ ]] || return 1
}

ValCity(){
	local city="$1"
	[[ "$city" =~ ^([a-zA-Z]{3,10})(\ [a-zA-Z]{3,10}){0,2}$ ]] || return 1;
}

ValServer(){
	local server="$1"
	[[ "$server" =~ ^[A-Z]{2}[-]?[A-Z]{0,4}#[1-9][0-9]{0,2}(-TOR)?$ ]] || return 1
}


ValPool(){
	local -a pool=("$@")
	local element
	(("${#pool[@]}" > 0 )) || return 1
	 
	for element in "${pool[@]}"; do
		if ValCountry "$element"; then
			continue
		elif ValCity "$element"; then
			continue
		elif ValServer "$element"; then
			continue
		else
			return 1
		fi
	done
}

ValOnOff(){
	local -a strings=("$@")
	local element
	for element in "${strings[@]}"; do
		[[ "$element" == "ON" || "$element" == "OFF" || "$element" == "NO" ]] || \
		 return 1
	done
}

ValMode(){
	local -a strings=("$@")
	local element
	for element in "${strings[@]}"; do
		[[ "$element" == "RANDOM" || "$element" == "ROUTE" ]] || \
		 return 1
	done
}

ValInteger(){
	local -a integers=("$@")
	local element
	
	for element in "${integers[@]}"; do
		[[ "$element" =~ ^[0-9]+$ ]] || return 1
	done
}

ValPercentage(){
	local -a percent=("$@")
	local element
	
	for element in "${percent[@]}"; do
		(( element >= 0 && element <= 100 )) || return 1
	done
}

ValConfig(){
	if ! ValPool "$MAIN_LOCATION"; then
		return 1
	fi
	
	if ! ValPool "${RANDOM_POOL[@]}"; then
		return 1
	fi
	
	if ! ValOnOff "$SWITCH_VPN_ONOFF" "$NOTIFY_ALLOFF" "$NOTIFY_VPN_ERROR_ONOFF" \
	"$NOTIFY_VPN_OK_ONOFF" "$NOTIFY_EXIT_ONOFF" "$NOTIFY_ASK_ONOFF" "$PROTON_INFO_ONOFF" \
	"$START_MESSAGE_ONOFF"; then
		return 1
	fi
	
	if ! ValMode "$MODE"; then
		return 1
	fi
	
	if ! ValInteger "$SECONDS_SWITCH_VPN_MAX" "$SECONDS_SWITCH_VPN_MIN" \
	"$PROBABILITY_SECURECORE" "$PROBABILITY_MAIN_LOCATION" "$MAX_CON_FAILS" \
	"$INCREASING_DELAY"; then
		return 1
	fi
	
	if ! ValPercentage "$PROBABILITY_SECURECORE" "$PROBABILITY_MAIN_LOCATION"; then
		return 1
	fi
	
	[[ "$SWITCH_VPN_ONOFF" == "ON" || "$SWITCH_VPN_ONOFF" == "OFF" ]] || return 1
	(( SECONDS_SWITCH_VPN_MIN < SECONDS_SWITCH_VPN_MAX )) || return 1
	
}





############## Output ##################################################

Out(){
	local text="$1"
	RunInTerminal && printf "%s\n" "$text"
}

OutErr(){
	local text="$1"
	RunInTerminal && printf '\033[38;5;196m%s\033[0m\n' "$text" >&2
}

OutH1() {
	local text="$1"
	RunInTerminal && printf '\n\033[38;5;38m%s\033[0m\n' "$text"
}

################ Notify ################################################

NotifyVpnError(){
	[[ "$NOTIFY_VPN_ERROR_ONOFF" == "ON" ]] || return 0
	local server="$1"
	notify-send --urgency=critical --app-name="$APPNAME" -- "$APPNAME" "${TXT_CON_ERROR}: $server"
}

NotifyVpnOk() {
	[[ "$NOTIFY_VPN_OK_ONOFF" == "ON" ]] || return 0
	local server="$1"
	notify-send --urgency=normal  --expire-time=10000 --app-name="$APPNAME" -- "$APPNAME" "${TXT_CON_OK} : $server"
}

NotifyAsk(){
	local title="$1"
	local question="$2"
	usrinp=$( notify-send --urgency=critical --app-name="$APPNAME" --action="y=yes" --action="n=no"  "$title" "$question" )
	[[ "$usrinp" == "y" ]] || return 1
}

MessageStart(){
	if RunInTerminal; then
		[[ "$PROTON_INFO_ONOFF" == "ON" ]] && VpnInfo
		[[ "$START_MESSAGE_ONOFF" == "ON" ]] && OutH1 "$TXT_MESSAGE_START"
	fi
}
	
############### Process control ########################################

cleanup() {
   exec 9>&- 
    exit
}

EnsureSingleInstance(){
	local lockfile
	lockfile="/tmp/${APPNAME}.${UID}.lock"
	trap cleanup EXIT TERM INT

exec 9>"$lockfile" || {
    OutErr "$TXT_LOCKFILE_ERROR" >&2
    exit 1
}

if ! flock -n 9; then
    OutErr "$TXT_RUN_ERROR $APPNAME" >&2
    exit 1
fi
}


RunInTerminal(){
if ! { [[ -t 1 && -n ${TERM:-} ]] && tput cols >/dev/null 2>&1; } then
	return 1
fi
}

############### protonvpn cli  #########################################

ProtonVpnConnect(){
	local dst="$1"
	local -a seccore=("$2")
	if ValCountry "$dst"; then
		protonvpn connect "${seccore[@]}" --country "$dst"  
	elif ValCity "$dst"; then
		protonvpn connect "${seccore[@]}" --city "$dst"
	elif ValServer "$dst"; then
		#no securecore !
		protonvpn connect "$dst"
	fi
}


KillSwitchOn(){
	if ! protonvpn config set kill-switch standard; then
		ExitHandler 12 "$TXT_KILLSWITCH_ERROR"
	fi
}


DisconnectVpn(){
	protonvpn disconnect
}


VpnInfo(){
	[[ "$PROTON_INFO_ONOFF" == "ON" ]] && protonvpn
}

############### KillSwitchGuard ########################################

AskPermissionKillSwitch(){
	local usrinp
	if [[ "$NOTIFY_ALLOFF" = "OFF" || "$NOTIFY_ASK_ONOFF" = "OFF" ]]; then
		if RunInTerminal; then
			while true; do
				read -rp "Enter: y or n >>" usrinp
				usrinp="${usrinp,,}"
				case "$usrinp" in
					y|yy|ye|yes)
						return 0
					;;	
					n|nn|no)
						return 1
					;;
				esac
			done
		fi
	else
		NotifyAsk "$TXT_ASK_KILLSWITCH_A" "$TXT_ASK_KILLSWITCH_B"
	fi
}
		
CheckConnection(){
	local status
	status="$(protonvpn status | awk 'tolower($0) ~ /status/ { print $2; exit }')"
	[[ "${status,,}" == "connected" ]] || return 1
}

CheckKillSwitch(){
	local killswitch
	killswitch="$( protonvpn config list   | awk 'tolower($0) ~ /kill-switch/ { print $2; exit }' )"
	[[ "${killswitch,,}" == "standard" ]] || return 1	
}

KillSwitchGuard(){
	if ! CheckKillSwitch; then
		if CheckConnection; then
			if AskPermissionKillSwitch; then
				DisconnectVpn
				KillSwitchOn
			fi
		else
			KillSwitchOn
		fi
	fi
}


	
		
################ Randomize VPN #######################################

RandomPercent(){
		printf  "%s\n" "$(( RANDOM % 100 + 1 ))"
	}
	
RandomSecureCore(){
	local securecore=""
	local r
	
	r="$( RandomPercent )"
	(( r <= PROBABILITY_SECURECORE )) && securecore="--securecore"
	
	printf "%s\n" "$securecore"
	
	}
			
RandomServer(){
	local r
	
	r="$( RandomPercent )"
	
	if (( r <= PROBABILITY_MAIN_LOCATION )); then
		server="$MAIN_LOCATION"
	else
		r="$(( RANDOM % ${#RANDOM_POOL[@]} ))"
		server="${RANDOM_POOL[$r]}"
	fi

	printf "%s\n" "$server"
}


RandomizeSwitchTime(){
	local max="$1"
	local min="$2"
	local seconds
	
	seconds=$(( RANDOM % (max - min + 1) + min ))	
	printf "%s" "$seconds" 
}

RandomModeVpn(){
	local server
	while true; do
		
		KillSwitchGuard
		
		server="$( RandomServer )"
		if ProtonVpnConnect "$server" "$( RandomSecureCore )"; then
			NotifyVpnOk "$server"
			
			[[ "$SWITCH_VPN_ONOFF" == "OFF" ]] && ExitHandler 0 "$TXT_SWITCH_OFF"
			count_fails="0"
		else
			NotifyVpnError "$server" 
			count_fails="$(( count_fails + 1 ))"
			wait_retry=$(( count_fails * INCREASING_DELAY ))
			(( count_fails <= MAX_CON_FAILS )) || ExitHandler 1 "$TXT_CON_FAILED"
			sleep "$wait_retry"
			continue
		fi
		SleepHandler "$( RandomizeSwitchTime $SECONDS_SWITCH_VPN_MAX $SECONDS_SWITCH_VPN_MIN )"
			
	done
}


RouteModeVpn(){
	local server
	while true; do
		for server in "${RANDOM_POOL[@]}"; do
		
			KillSwitchGuard
			
			if ProtonVpnConnect "$server" "$( RandomSecureCore )"; then
				count_fails="0"
				NotifyVpnOk "$server"
				[[ "$SWITCH_VPN_ONOFF" == "OFF" ]] && ExitHandler 0 "$TXT_SWITCH_OFF"
			else
				NotifyVpnError "$server" 
				count_fails="$(( count_fails + 1 ))"
				wait_retry=$(( count_fails * INCREASING_DELAY ))
				(( count_fails <= MAX_CON_FAILS )) || ExitHandler 1 "$TXT_CON_FAILED"
				sleep "$wait_retry"
				continue
			fi
			SleepHandler "$( RandomizeSwitchTime $SECONDS_SWITCH_VPN_MAX $SECONDS_SWITCH_VPN_MIN )"	
			
		done
	done
}
			

#--------------- Functions Handler ------------------------------------#

SleepHandler(){
		local seconds="$1"
		local i
		if RunInTerminal; then	
			for (( i=0; i < seconds; i++ )); do
				Out "-- $(( seconds - i )) -- $TXT_SLEEP_HANDLER "
				sleep 1
				tput cuu1
				tput el
			done
		else
			sleep "$seconds"
		fi
	}
	
ExitHandler(){
	local errcode="$1"
	local text="$2"
	
	if DepCheck "notify-send"; then
		[[ "$NOTIFY_EXIT_ONOFF" == "ON" ]] && \
		notify-send --urgency=critical --app-name="$APPNAME" "$APPNAME" "$text - $TXT_EXIT_HANDLER"
	fi
	
	if (( errcode < 1 )); then
		Out "$text"
	else
		OutErr "$text"
	fi
	
	exit "$errcode"
}

#----------------------------------------------------------------------#

main(){
	local count_fails=0
	local wait_retry=1
	
	MessageStart
	
	if [[ "$MODE" == "RANDOM" ]]; then
		RandomModeVpn
	elif [[ "$MODE" == "ROUTE" ]]; then
		RouteModeVpn
	fi

}

#----------------------------------------------------------------------#
ValConfig || ExitHandler 11 "Well played... You made the config invalid"

if  [[ "$NOTIFY_ALLOFF" == "ON" && \
	"$NOTIFY_VPN_ERROR_ONOFF" == "OFF" && \
	"$NOTIFY_VPN_OK_ONOFF" == "OFF" && \
	"$NOTIFY_EXIT_ONOFF" == "OFF" && \
	"$NOTIFY_ASK_ONOFF" == "OFF" ]]; then
	NOTIFY_ALLOFF="OFF"
fi

[[ "$NOTIFY_ALLOFF" != "OFF" ]] && \
{ DepCheck "notify-send" || ExitHandler 10  "$TXT_REQUIRED_NOTIFY"; }
DepCheck "tput" || ExitHandler 10  "$TXT_REQUIRED_TPUT"
DepCheck "awk" || ExitHandler 10 "$TXT_REQUIRED_AWK"
DepCheck "protonvpn" || ExitHandler 10 "$TXT_REQUIRED_PROTON"

EnsureSingleInstance 
ParseCommandLineOptions "$@"

main
